# Generated by Django 3.2.5 on 2022-07-04 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0002_dweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='likes',
            field=models.ManyToManyField(related_name='dweet_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
